@startuml
'https://plantuml.com/class-diagram
package java{
    class Handler{
        mLooper:Looper
        mQueue:MessageQueue

        + dispatchMessage():void
        + post(r:Runnable):boolean
    }

    interface Callback{
        + handleMessage(msg:Message):boolean
    }

    class MessageQueue{
        - mPtr:long
        next():Message
    }

    class Message{}

    class Looper{
        mQueue:MessageQueue
    }

    Looper *-- MessageQueue
    Callback --* Handler

    Handler --> MessageQueue
    Handler --> Looper

    Message --* MessageQueue
}

package jni{

 class android_os_MessageQueue{

 }
}

package native{

    class NativeMessageQueue{

    }

    class "Looper" as NativeLooper{
    }


}
android_os_MessageQueue <-- MessageQueue

android_os_MessageQueue --> NativeMessageQueue


NativeLooper --* NativeMessageQueue


@enduml