@startuml
'https://plantuml.com/class-diagram


package flutter {

    abstract Widget
    abstract class StatefulWidget
    abstract class StatelessWidget

     abstract class SingleChildStatefulWidget
     abstract class SingleChildStatelessWidget

     Widget <|-- StatefulWidget
     Widget <|-- StatelessWidget

    StatefulWidget <|-- SingleChildStatefulWidget
    StatelessWidget <|-- SingleChildStatelessWidget
}


package bloc{
    abstract class BlocBase<State>
    abstract class Bloc<Event, State>

    abstract class Emittable
    abstract class Closable
    abstract class ErrorSink
    abstract class StateStreamableSource

    abstract class Streamable
    abstract class StateStreamable
    abstract class BlocObserver
'    class _DefaultBlocObserver

    abstract class Emitter<State>

    class _Emitter<State>
    class _Handler
    class Change<State>
    class Transition<Event,State>
    Change <|-- Transition

    BlocBase <|-- Bloc
    StateStreamableSource <|.. BlocBase
    Emittable <|.. BlocBase
    ErrorSink <|.. BlocBase
    Closable <|.. ErrorSink
    Streamable <.. StateStreamable
    StateStreamable <.. StateStreamableSource
    Bloc *-- BlocObserver

    Emitter <|.. _Emitter

    Bloc "1"*--"n" _Emitter
    Bloc "1"*--"n" _Handler
}

package provider{
    class InheritedProvider
}

package flutter_bloc {

    abstract class BlocBuilderBase
    abstract class BlocListenerBase
    class BlocListener
    class BlocProvider
    class BlocBuilder

    BlocListenerBase <|-- BlocListener
    BlocBuilderBase <|-- BlocBuilder
}

InheritedProvider <.. BlocProvider

'package demo{
'
'    class DemoPage
'    class DemoBloc
'
'}
'
'DemoPage *-- BlocListener
'DemoPage *-- BlocBuilder
'DemoPage *-- BlocProvider
'Bloc <|-- DemoBloc

SingleChildStatefulWidget <|-- BlocListenerBase
SingleChildStatelessWidget <|-- BlocProvider
StatefulWidget <|-- BlocBuilderBase



BlocProvider *-- StateStreamableSource
BlocBuilderBase *-- StateStreamable
BlocListenerBase *-- StateStreamable

SingleChildStatelessWidget <|-- InheritedProvider
@enduml