@startuml
'https://plantuml.com/class-diagram

abstract class SingleChildStatelessWidget
abstract class InheritedWidget

class _InheritedProviderScope
class InheritedProvider

abstract class _Delegate
class _CreateInheritedProvider

InheritedWidget <|-- _InheritedProviderScope

SingleChildStatelessWidget <|-- InheritedProvider
InheritedProvider *-- _Delegate
_InheritedProviderScope <.. InheritedProvider
_Delegate <|-- _CreateInheritedProvider


@enduml