@startuml
'https://plantuml.com/class-diagram

package bloc{
    class BlocBase
    class Bloc

    abstract class Emittable
    abstract class Closable
    abstract class ErrorSink
    abstract class StateStreamableSource

    abstract class Streamable
    abstract class StateStreamable
    abstract class BlocObserver
    class _DefaultBlocObserver
}

BlocBase <|-- Bloc
StateStreamableSource <|.. BlocBase
Emittable <|.. BlocBase
ErrorSink <|.. BlocBase
Closable <|.. ErrorSink

Streamable <.. StateStreamable
StateStreamable <.. StateStreamableSource

BlocObserver <|-- _DefaultBlocObserver

package flutter_bloc {

    abstract class BlocBuilderBase
    abstract class BlocListenerBase
    class BlocListener
    class BlocProvider
    class BlocBuilder
}

package flutter {
    class SingleChildStatefulWidget
    class SingleChildStatelessWidget
    class StatefulWidget
}

SingleChildStatefulWidget <|-- BlocListenerBase
SingleChildStatelessWidget <|-- BlocProvider
StatefulWidget <|-- BlocBuilderBase

BlocListenerBase <|-- BlocListener
BlocBuilderBase <|-- BlocBuilder

BlocProvider *-- StateStreamableSource
BlocBuilderBase *-- StateStreamable

Bloc *-- BlocObserver

package demo{

    class Page{}
}

Page *-- BlocListener
Page *-- BlocBuilder
@enduml