@startuml
'https://plantuml.com/sequence-diagram

interface Executor{}
interface ExecutorService{}
interface ScheduledExecutorService{}
abstract class AbstractExecutorService{}
class ThreadPoolExecutor{}
class ScheduledThreadPoolExecutor{}
class ForkJoinPool{}


interface Runnable{}
abstract class AbstractOwnableSynchronizer{}
abstract class AbstractQueuedSynchronizer{}
class Worker{}

class Thread{}


Runnable <|.. Worker
AbstractQueuedSynchronizer <|-- Worker
AbstractOwnableSynchronizer <|-- AbstractQueuedSynchronizer
ThreadPoolExecutor *-- Worker
ThreadPoolExecutor <|-- ScheduledThreadPoolExecutor
ScheduledExecutorService <|.. ScheduledThreadPoolExecutor
ExecutorService <|-- ScheduledExecutorService


Executor <|-- ExecutorService
ExecutorService <|.. AbstractExecutorService
AbstractExecutorService <|-- ThreadPoolExecutor
AbstractExecutorService <|-- ForkJoinPool


Worker *--Thread
@enduml